disabled_rules:
- vertical_whitespace
- line_length
- function_body_length
- cyclomatic_complexity
- comment_spacing
- force_cast
- trailing_whitespace
- unused_closure_parameter
- inclusive_language
- control_statement
- mark

opt_in_rules:
- opening_brace
